accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "WTFPL",
    "Zlib",
    "BSL-1.0",
    "CC0-1.0",
    "OFL-1.1",
    "bzip2-1.0.6",
    "MPL-2.0",
    "NCSA",
    "ISC",
    "Apache-2.0 WITH LLVM-exception",
    "Ubuntu-font-1.0"
]
